
CHR=$1                                  # chromosome chr{1..18}
ADDAC_VCF=${CHR}.addAC.vcf.gz           # Generated by the previous step code 01.WGS_variant_calling.sh；filtered + AC/AN annotated VCF
PEDIGREE= F2.pedigree.fam.revise        # pedigree file
THREADS=50                              # default threads

# Run SHAPEIT5 (phase_common_static)
# --------------------------
singularity exec /home/guilu/software/shapeit5.simg phase_common_static \
    --input ${ADDAC_VCF} \
    --pedigree ${PEDIGREE} \
    --region ${CHR} \
    --thread ${THREADS} \
    --log ${CHR}.shapeit.log \
    --output ${CHR}.shapiet.bcf

# Convert BCF to gzipped VCF and index
bcftools view ${CHR}.shapiet.bcf | bgzip -@ ${THREADS} -c > ${CHR}.shapiet.vcf.gz
tabix -p vcf ${CHR}.shapiet.vcf.gz
