#!/usr/bin/env bash
set -euo pipefail


# --------------------------
# Parameters
# --------------------------
OUTPUT=/path/to/output
INPUT=/path/to/phased_BAMs
GTF=Sus_scrofa.Sscrofa11.1.100.gtf
THREADS=40

# Select BAM list file
BAMLIST= F2.JR.Phased.bamfiles    # Generated by the previous step code 04.
###Example lines in the list:
path/F2-1000.RNAphased.bam
path/F2-1000.Hap1.bam
path/F2-1000.Hap2.bam

# --------------------------
# Loop over all samples in the list
# --------------------------
while read -r ID BAM; do

    singularity exec -B ${INPUT}:${INPUT} /home/guilu/software/star_2.7.9a_subread.simg featureCounts \
        -T ${THREADS} \
        -p -t gene \
        -g gene_id \
        -a ${GTF} \
        -o ${OUTPUT}/${ID}.featureCounts.txt \
        -s 2 \
        ${INPUT}/${BAM}

    echo "[$(date)] Finished sample: ${ID}"
done < ${BAMLIST}


